# Site settings
sparkversion: 2.7.1
templateversion: 2.7.1
description: > # > means to ignore newlines as long as indent is kept
  Spark Framework - Create web applications in Java rapidly. 
  Spark is a micro web framework that lets you focus on writing your code, not boilerplate code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sparktutorials.github.io" # the base hostname & protocol for your site
twitter_username: sparkjava
gems: [jekyll-redirect-from]

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
